//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashVerifier.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en_GB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashVerifier.lang.en-GB", typeof(en_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the cryptographic algorithm for verification.
        /// </summary>
        internal static string algo_select_notice {
            get {
                return ResourceManager.GetString("algo_select_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow.This file has not been modified.  it is Safe if the the hash you input is correct.
        /// </summary>
        internal static string CorrectMessage {
            get {
                return ResourceManager.GetString("CorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Website.
        /// </summary>
        internal static string devloper_info {
            get {
                return ResourceManager.GetString("devloper_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits left:.
        /// </summary>
        internal static string Digits_left {
            get {
                return ResourceManager.GetString("Digits_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a File.
        /// </summary>
        internal static string file_progress_label {
            get {
                return ResourceManager.GetString("file_progress_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type the Hash String.
        /// </summary>
        internal static string hash_input_label {
            get {
                return ResourceManager.GetString("hash_input_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then type the Hash String here.
        /// </summary>
        internal static string input_label {
            get {
                return ResourceManager.GetString("input_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made By FortyIX.
        /// </summary>
        internal static string maker_name {
            get {
                return ResourceManager.GetString("maker_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Prograss.
        /// </summary>
        internal static string progress_label {
            get {
                return ResourceManager.GetString("progress_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string select_btn {
            get {
                return ResourceManager.GetString("select_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Selecte a file first.
        /// </summary>
        internal static string select_label {
            get {
                return ResourceManager.GetString("select_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a cryptographic algorithm.
        /// </summary>
        internal static string select_status {
            get {
                return ResourceManager.GetString("select_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify !.
        /// </summary>
        internal static string submit_button {
            get {
                return ResourceManager.GetString("submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileVerifier.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Err,Changes have been found in this file. your computer may face risk if you install this software.
        /// </summary>
        internal static string WrongMessage {
            get {
                return ResourceManager.GetString("WrongMessage", resourceCulture);
            }
        }
    }
}
