//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashVerifier.lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class zh_CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal zh_CN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashVerifier.lang.zh-CN", typeof(zh_CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择一种用来校检的加密算法.
        /// </summary>
        internal static string algo_select_notice {
            get {
                return ResourceManager.GetString("algo_select_notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有发现任何文件更改，如果哈希字符串输入正确，这个文件是安全的.
        /// </summary>
        internal static string CorrectMessage {
            get {
                return ResourceManager.GetString("CorrectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开发者网站.
        /// </summary>
        internal static string devloper_info {
            get {
                return ResourceManager.GetString("devloper_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 剩余位数：.
        /// </summary>
        internal static string Digits_left {
            get {
                return ResourceManager.GetString("Digits_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个文件.
        /// </summary>
        internal static string file_progress_label {
            get {
                return ResourceManager.GetString("file_progress_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入哈希值.
        /// </summary>
        internal static string hash_input_label {
            get {
                return ResourceManager.GetString("hash_input_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 然后输入一个哈希字符串.
        /// </summary>
        internal static string input_label {
            get {
                return ResourceManager.GetString("input_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FortyIX制作.
        /// </summary>
        internal static string maker_name {
            get {
                return ResourceManager.GetString("maker_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入进度.
        /// </summary>
        internal static string progress_label {
            get {
                return ResourceManager.GetString("progress_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择.
        /// </summary>
        internal static string select_btn {
            get {
                return ResourceManager.GetString("select_btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个文件.
        /// </summary>
        internal static string select_label {
            get {
                return ResourceManager.GetString("select_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择一个加密算法.
        /// </summary>
        internal static string select_status {
            get {
                return ResourceManager.GetString("select_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校验 !.
        /// </summary>
        internal static string submit_button {
            get {
                return ResourceManager.GetString("submit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件校验器.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件更改发现 ！继续安装此软件可能导致您的电脑面临风险.
        /// </summary>
        internal static string WrongMessage {
            get {
                return ResourceManager.GetString("WrongMessage", resourceCulture);
            }
        }
    }
}
